### ISSUE TITLE
能否支持编译呢？

### ISSUE THREAD

**Issue by langqinqieyi** [Rtoax/linux-5.10.13#1]
已经完全不可能编译，还是实现这个时间成本太高呢？
如果可以支持编译，可否出一个编译手册，或者直接在另外一个分支提供编译支持？

**Comment by Rtoax** [comment]
很抱歉，从最初上传就没考虑编译问题，在注释过程没考虑编译因素，直接用上游代码吧











***@***.***&gt;

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月4日(周一) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Rtoax/linux-5.10.13] 能否支持编译呢？ (Issue #1)




 
已经完全不可能编译，还是实现这个时间成本太高呢？
 如果可以支持编译，可否出一个编译手册，或者直接在另外一个分支提供编译支持？

**Comment by Rtoax** [comment]
如果没有其他疑问，我就关闭这个issue了，谢谢！
